/*
 * API Falabella FIF
 * Esta API esta diseñada para ser una prueba para los nuevos candidatos al equipo.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lugaetea@falabella.cl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * BeerBox
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-23T12:50:09.794-03:00[America/Santiago]")public class BeerBox {

  @SerializedName("Price Total")
  private BigDecimal priceTotal = null;
  public BeerBox priceTotal(BigDecimal priceTotal) {
    this.priceTotal = priceTotal;
    return this;
  }

  

  /**
  * Get priceTotal
  * @return priceTotal
  **/
  @Schema(description = "")
  public BigDecimal getPriceTotal() {
    return priceTotal;
  }
  public void setPriceTotal(BigDecimal priceTotal) {
    this.priceTotal = priceTotal;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeerBox beerBox = (BeerBox) o;
    return Objects.equals(this.priceTotal, beerBox.priceTotal);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(priceTotal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeerBox {\n");
    
    sb.append("    priceTotal: ").append(toIndentedString(priceTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
