/*
 * API Falabella FIF
 * Esta API esta diseñada para ser una prueba para los nuevos candidatos al equipo.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lugaetea@falabella.cl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BeerBox;
import io.swagger.client.model.BeerItem;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CervezaApi
 */
@Ignore
public class CervezaApiTest {

    private final CervezaApi api = new CervezaApi();

    /**
     * Ingresa una nueva cerveza
     *
     * Ingresa una nueva cerveza
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addBeersTest() throws ApiException {
        BeerItem body = null;
        api.addBeers(body);

        // TODO: test validations
    }
    /**
     * Lista el precio de una caja de cervezas de una marca
     *
     * Obtiene el precio de una caja de cerveza por su Id 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void boxBeerPriceByIdTest() throws ApiException {
        Integer beerID = null;
        String currency = null;
        Integer quantity = null;
        api.boxBeerPriceById(beerID, currency, quantity);

        // TODO: test validations
    }
    /**
     * Lista el detalle de la marca de cervezas
     *
     * Busca una cerveza por su Id 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchBeerByIdTest() throws ApiException {
        Integer beerID = null;
        api.searchBeerById(beerID);

        // TODO: test validations
    }
    /**
     * Lista todas las cervezas
     *
     * Lista todas las cervezas que se encuentran en la base de datos
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchBeersTest() throws ApiException {
        List<BeerItem> response = api.searchBeers();

        // TODO: test validations
    }
}
